- project:
    name: 'infra'
    is-disabled: ''

    maintain-node: 'new-builder'

    distro:
    - trusty:
        os: ubuntu
        mos_version: '9.0'
    - xenial:
        os: ubuntu
        mos_version: '10.0'

    timeout: 60

    jobs:
    - 'infra-trigger-docker-image-{os}-{distro}'

    - 'infra-build-docker-image-{os}-{distro}'

    - 'infra-run-docker-tox-{tox-env}':
        tox-env:
        - pep8
        - py27
        - py34
        - py35
        - functional
